### ISSUE TITLE
Successfully faxed job return error in Windows 10 (SPI type = windows)

### ISSUE THREAD

**Issue by AnthonySTHO** [sagiegurari/fax4j#10]
when I set org.fax4j.spi.default.type=windows in fax4J.properties, successfully faxed job will return the message below and the program stopped :
```
019-07-17 14:34:42.787,92413,[ERROR],org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler.handleError,"Unexpected error occurred in scheduled task." org.fax4j.FaxException: Error while invoking fax4j.exe, error: Unable to extract fax job info - ERROR_INVALID_PARAMETER
Native Output:
[fax4j-native][DEBUG] Debug mode enabled.
[fax4j-native][DEBUG] Checking argument:
[fax4j-native][DEBUG] -action
[fax4j-native][DEBUG] Argument value:
[fax4j-native][DEBUG] getstatus
[fax4j-native][DEBUG] Checking argument:
[fax4j-native][DEBUG] -job
[fax4j-native][DEBUG] Argument value:
[fax4j-native][DEBUG] 327
[fax4j-native][DEBUG] Read input:
[fax4j-native][DEBUG] Action:
[fax4j-native][DEBUG] getstatus
[fax4j-native][DEBUG] Server:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] Fax Job ID:
[fax4j-native][DEBUG] 327
[fax4j-native][DEBUG] Target Address:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] Target Name:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] Sender Name:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] File:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] Document Name:
[fax4j-native][DEBUG] (null)
[fax4j-native][DEBUG] Handling specific fax action.
[fax4j-native][DEBUG] Invoking cancelFaxJobNative
[fax4j-native][DEBUG] Invoking getFaxJobStatus
[fax4j-native][DEBUG] Connecting to fax server.
[fax4j-native][DEBUG] Error Code: 87 Message: Unable to extract fax job info - ERROR_INVALID_PARAMETER 
fax.operation.done=false
fax.error=Unable to extract fax job info - ERROR_INVALID_PARAMETER

	at org.fax4j.spi.windows.WindowsProcessOutputValidator.validateProcessOutput(WindowsProcessOutputValidator.java:87)
	at org.fax4j.spi.process.ProcessFaxClientSpi.validateProcessOutput(ProcessFaxClientSpi.java:566)
	at org.fax4j.spi.process.ProcessFaxClientSpi.executeProcess(ProcessFaxClientSpi.java:492)
	at org.fax4j.spi.process.ProcessFaxClientSpi.getFaxJobStatusImpl(ProcessFaxClientSpi.java:422)
	at org.fax4j.spi.AbstractFaxClientSpi.getFaxJobStatus(AbstractFaxClientSpi.java:397)
	at org.fax4j.spi.adapter.AbstractAdapterFaxClientSpi.getFaxJobStatusImpl(AbstractAdapterFaxClientSpi.java:146)
	at org.fax4j.spi.windows.WindowsFaxClientSpi.getFaxJobStatusImpl(WindowsFaxClientSpi.java:271)
	at org.fax4j.spi.AbstractFaxClientSpi.getFaxJobStatus(AbstractFaxClientSpi.java:397)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.fax4j.spi.AbstractFaxClientSpiProxy.invoke(AbstractFaxClientSpiProxy.java:203)
	at com.sun.proxy.$Proxy78.getFaxJobStatus(Unknown Source)
	at org.fax4j.FaxClient.getFaxJobStatus(FaxClient.java:262)
	at hk.gov.dh.dental.autofax.controller.FaxEngine.sendFaxViaFax4J(FaxEngine.java:160)
	at hk.gov.dh.dental.autofax.controller.FaxEngine.sendFax(FaxEngine.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

My code, exception thrown at 1st line, it seems that faxJob is not valid anymore once the job has been done and removed in the fax queue, I have rewritten it with try-catch surrounding faxClient.getFaxJobStatus(faxJob) but the result is the same. :

```
while (faxClient.getFaxJobStatus(faxJob) == FaxJobStatus.PENDING || faxClient.getFaxJobStatus(faxJob) == FaxJobStatus.IN_PROGRESS) {
	i++;
	log.info("STATUS: " + faxClient.getFaxJobStatus(faxJob).toString());
	try {
		Thread.sleep(500);
	} catch (InterruptedException ex) {
		log.error("Error sleep: " + ex.getMessage(), ex);
	}
	log.trace(".");
}
```

**Comment by sagiegurari** [comment]
that happen when windows is not familiar with the fax job id if i'm not wrong.
that could happen if the fax job completed already and windows removed it from its queue.
in your case it means (if you sending it was ok) that it completed.
My api is really limited due to how windows works :(
