### ISSUE TITLE
Excuse me?Why is this。

### ISSUE THREAD

**Issue by afunnyrainman** [sagiegurari/fax4j#37]
Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/cobertura/coveragedata/TouchCollector
	at org.fax4j.FaxClientFactory.__cobertura_init(FaxClientFactory.java)
	at org.fax4j.FaxClientFactory.<clinit>(FaxClientFactory.java)
	at Text.main(Text.java:21)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

**Comment by sagiegurari** [comment]
feels like you are using the coverage test jar and not the fax4j jar created in the target dir.
